# This file defines ONLY the Redis service.
# The Node.js app runs locally, and MongoDB is on Atlas.

services:
  redis:
    image: redis:7-alpine
    container_name: crypto-crash-redis
    ports:
      # Exposes the Redis container's port 6379 to your computer's port 6379
      - "6379:6379"
    volumes:
      # Persists Redis data so it's not lost when the container stops
      - redisdata:/data

volumes:
  redisdata: